### ISSUE TITLE
Add SOQL Datatable to Community / Experience Cloud page context

### ISSUE THREAD

**Issue by sderenSFDC** [tsalb/lwc-utils#109]
Is there a reason behind the components in this repo not targeting community pages?  Wondering if there are any known limitations, etc.

**Comment by tsalb** [comment]
Great question. Short answer is "yes, initially", due to some confidence jarring decisions by the SFDC PMs on walking back LMS in Community (Experience) context.

That being said, my internal fork of `soqlDatatable` does have the community page definition (my use case is for authorized users, I do not have any experience with guest site user in this context).

Coincidentally, I wanted to make some time and release the community xml definition to a few components and this FR gives me an excuse to do that.

Going ahead and changing the title of this and moving to `enhancement`

**Comment by sderenSFDC** [comment]
Thank you, makes sense.
