### ISSUE TITLE
SOQL Datatable - fetchTableCache error in Sandbox Org

### ISSUE THREAD

**Issue by alan-craftbrewerysolutions** [tsalb/lwc-utils#42]
Where: Aggregate SOQL Datatable Tab - 2nd datatable
Complete message:
fetchTableCache error
Attempt to de-reference a null object Class.DataTableService.getColumnData: line 317, column 1 Class.DataTableService.getTableCache: line 197, column 1

Installed Utils and then Recipes.

This is in a Trailhead Org (if it matters).

**Comment by tsalb** [comment]
Thanks @alan-craftbrewerysolutions - do you happen to know the steps to create the trailhead org to repro this? The recipes were developed in "clean-room" (scratch org only) so it was bound to hit some issues in sandboxes with existing data (and features turned on).

If you know which Trailheads were used to create your org (sample data etc) and I can get a good idea of your:
- Opportunity data (schema).
- Any features turned on in the org that affects Opportunity.

That would be useful for some debugging!

Alternatively, I will put a note here that I may want to use a different example (a different sobject) due to org variations.

**Comment by alan-craftbrewerysolutions** [comment]
@tsalb I created a new playground just for taking a look at the package. I then used the playground package installer with id 04t1Q000001QhnjQAC (sandbox id from readme). 

Everything else is working fine. I was able to run the soql in the console fine. The error happens on the Aggregate SOQL Datatable tab. The query is:

SELECT SUM(ExpectedRevenue) Max_Revenue, FISCAL_YEAR(CloseDate) Close_Date_Year, FISCAL_MONTH(CloseDate) Close_Date_Month FROM Opportunity GROUP BY CloseDate

This is not a hold up for me so you can close the bug. Let me know if you need anything else.

**Comment by tsalb** [comment]
Thanks for that update - i'll create a default playground (haven't done so in ages) and see what happens there.

By any chance, do you recall the exact trailhead module you started the playground from? I vaguely remember that all playgrounds are the same, but if for some reason a playground started on a specific module is different - that would be a good piece of data.

**Comment by alan-craftbrewerysolutions** [comment]
It was a brand new playground. I just created it from the list of playgrounds, not from any module. Maybe that's the problem.

Also, I tried installing in a named dev org I have. Won't let me. Do you know any work-around?

**Comment by tsalb** [comment]
@alan-craftbrewerysolutions

Which package version (Id) did you install and by `named dev org` did you mean an org with my domain enabled?

**Comment by tsalb** [comment]
Closing this out for inactivity
