### ISSUE TITLE
Collection Datatable - Output Selected Rows and rows not selected/edited

### ISSUE THREAD

**Issue by Feldstrom** [tsalb/lwc-utils#45]
Would love to have the option to output both the selected/edited rows and the rows that were not selected into separate collections. 

When displaying a collection of record to end user, I want to do work to any records selected by the user and identify the ones they did not select for a separate task.

There is currently a way to do this in flow using two loops and a decision to pull any records not in the selected collection out into a new collection.

**Comment by tsalb** [comment]
This is very interesting, it's not often someone wants to process **unselected** rows.

I could potentially see some scalability issues if the SOQL statement uses a high LIMIT 1000 (when user defines their own limit, it supersedes the default LIMIT I set in place).

In those situations, unselected rows could be in the hundreds (thousands). What is the data volume in your use case?

**Comment by Feldstrom** [comment]
Data volume is likely not to exceed 100 rows per collection.

**Comment by tsalb** [comment]
I am inclined to let the user shoot themselves in the foot with this FR, allowing to return whatever collection was passed **into** view, to be extracted out (but as you said, in separate collections).

If the UI breaks because you passed in 10,000 rows - that is on the solution designer to fix that - not the UI component.

I think this is feasible, no ETA though!

**Comment by tsalb** [comment]
Closing as duplicate in the above issue
