### ISSUE TITLE
SOQL / Collection Datatable - Allow custom relative height in Screen Flows

### ISSUE THREAD

**Issue by Feldstrom** [tsalb/lwc-utils#49]
For the collection datatable it is currently not possible to set a custom relative hight leading to issues with UX as seen in video attached.

https://user-images.githubusercontent.com/30249667/103720285-e23cac00-4f7f-11eb-8830-2094f2f0709b.mov

**Comment by tsalb** [comment]
Yep, as we discussed offline (of github) - the root cause is my decision to attach interactivity from within the cell itself - allowing me to control overflow vertically but within the bounds of the table.

There is a more complicated approach, one similar to SFDC list views which is to attach a hidden overlay to dynamically attach "popovers" which track the x-y coordinates of where the cell interactivity is launched from. This is too high LOE for my liking so we are stuck with....

The workaround is to specify a minimum height (which is a feature for `soqlDatatable`).

I'll port that over and add a disclaimer on the README for this behavior.

**Comment by tsalb** [comment]
Note to self - since screen flows can be limited in space (depending on if they're launched from flexipage, quick action, etc) it might be better to just add a "Table Height (px)" property with a default of `null` which solution designers can configure.

This is different than relative max height since that uses `vh` to calculate height and this one would use `px`

**Comment by tsalb** [comment]
I am wrong about the height thing being able to fix this.

That does indeed extend the container of the table however it doesn't affect the dropdown from the picklist. I am going to evaluate including a experimental checkbox that does a CSS hack that allows for overflow - but it has some caveats I'd like to document before introducing it.
