### ISSUE TITLE
SOQL Datatable - Output selected recordIds in its own output

### ISSUE THREAD

**Issue by solo-1234** [tsalb/lwc-utils#61]
I have a soql datatable on a record page which has a button that calls a flow and passes in the selected records. Since fields from parent records aren't included during the handoff, I'm going to run my own query inside the flow to fetch them. What do you think about passing in a text-collection of record ids in addition to the record collection? That would save a step (extracting their Ids from the collection) in my flow.

**Comment by tsalb** [comment]
Related to #45 under the general request of "more output types".

I am not sure where I want to go with this yet because it can be a slippery slope - add more of these parsing features inside my lib OR wait until the platform matures to be able to extract them from flow more natively.

I am leaning on the latter but stay tuned for further updates!

**Comment by solo-1234** [comment]
Right I hear that!

Another idea along the same lines would be if flows were not required to create all the input vars that the datatable can send; instead allow the admin to create vars for whichever pieces of information they will need in the flow.

I don't know what technical limitations are involved in that but it would be a nice enhancement if not a big deal.

**Comment by tsalb** [comment]
> Another idea along the same lines would be if flows were not required to create all the input vars that the datatable can send; instead allow the admin to create vars for whichever pieces of information they will need in the flow.

This is probably easier solved in the FAQ / WIKI for the moment

**Comment by solo-1234** [comment]
Short term: definitely
Long term: you may want to consider actually making them optional. I just created a new flow to be used as a table action and ended up cloning an old one to save all the work of creating those four input vars.

**Comment by tsalb** [comment]
@solo-1234 for this piece, I would recommend creating a template that has all 4 variables that are required.

Due to the way I am handing it off, it is much easier to recommend to everyone **always** create these variables as to **only sometimes** create these variables. As of right now, I don't believe it is (easily) technically feasible to determine if the component is currently being used inside flow or on a flexipage.

Additionally, I don't want to introduce code bloat for checking that (just yet).

I'd say this is off topic for this specific FR though - if you'd like to submit another issue around this let's continue conversation in another issue!

**Comment by tsalb** [comment]
Closing this as duplicate in the above issue

**Comment by solo-1234** [comment]
good idea!
